services:
  # server:
  #   build:
  #     context: ./server
  #   env_file:
  #     - ./server/.env
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - postgres
  #   command: sh -c "sleep 4 && npm start"
  #   networks:
  #     - networkA
  postgres:
    build:
      context: ./database
    env_file:
      - ./database/.env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-storage:/var/lib/postgressql/data
    networks:
      - networkA
  mailslurper:
    image: marcopas/docker-mailslurper
    container_name: mailslurper
    ports:
      - "2500:2500"
      - "8182:8080"
      - "8085:8085"
    restart: unless-stopped  # Optional: Ensures the container restarts automatically unless manually stopped
    stdin_open: true   # Equivalent to -i in Docker run
    tty: true          # Equivalent to -t in Docker run
volumes:
  postgres-storage:

networks:
  networkA: